name : PHPUnit

on :
  [ push, pull_request ]

jobs :
  phpunit :
    runs-on : ubuntu-latest

    services :
      mysql :
        image : mysql:5.7
        env:
          MYSQL_DATABASE: 'manager'
          MYSQL_USER: 'manager'
          MYSQL_PASSWORD: 'manager'
          MYSQL_ROOT_PASSWORD: 'manager'
        ports :
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy :
      fail-fast : true
      matrix :
        php : [ '7.4' ]

    name: PHP ${{ matrix.php }}

    steps :
      - name: Checkout the Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: xml, curl
          tools: composer:v2

      - name : Copy .env
        run : php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name : Install Dependencies
        run : composer install

      - name : Laravel Preparation
        run : |
          php artisan key:generate
          php artisan optimize
          php artisan cache:clear
          php artisan config:cache

      - name : Database Preparation
        run : php artisan migrate

      - name : JS/CSS Preparation
        run : |
          npm install
          npm run dev

      - name : Testing
        run : php artisan test --coverage-clover=coverage.xml

      - name : Upload CodeCoverage
        run : bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}